services:
  - type: web
    name: taximela-otp
    env: docker
    dockerfilePath: ./Dockerfile.otp
    plan: starter
    region: oregon
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx1G -server"
      - key: PORT
        value: "8080"
    healthCheckPath: /otp/routers/default